language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rtakeshi1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rtakeshi1/react-test npm test -- --coverage

after_success:
  - docker build -t rtakeshi1/multi-client ./client
  - docker build -t rtakeshi1/multi-nginx ./nginx
  - docker build -t rtakeshi1/multi-server ./server
  - docker build -t rtakeshi1/multi-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push built images to docker hub
  - docker push rtakeshi1/multi-client
  - docker push rtakeshi1/multi-nginx
  - docker push rtakeshi1/multi-server
  - docker push rtakeshi1/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-179668140295
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY